module.exports = {
  CHAT_TOPIC: 'universal-connectivity',
  CHAT_FILE_TOPIC: 'universal-connectivity-file',
  PUBSUB_PEER_DISCOVERY: 'universal-connectivity-browser-peer-discovery',
  FILE_EXCHANGE_PROTOCOL: '/universal-connectivity-file/1',
  DIRECT_MESSAGE_PROTOCOL: '/universal-connectivity/dm/1.0.0',
  STREAM_SIGNAL_WRAPPER: 'stream-signal',
  STREAM_SIGNAL_APP_ID: 'metered',
  STREAM_SIGNAL_TOPIC: 'universal-connectivity',
  STREAM_CHAT_TOPIC: 'universal-connectivity',
  AGENT_SIGNAL_WRAPPER: 'agent-signal',
  AGENT_SIGNAL_APP_ID: 'metered-agent',
  AGENT_SIGNAL_TOPIC: 'universal-connectivity',
  AGENT_CHAT_TOPIC: 'universal-connectivity',
  CALL_SIGNAL_WRAPPER: 'call-signal',
  CALL_SIGNAL_APP_ID: 'metered-call',
  CALL_SIGNAL_TOPIC: 'universal-connectivity',
  CHAT_MESSAGE_WRAPPER: 'metered-chat',
  CHAT_MESSAGE_APP_ID: 'metered',
  LM_STUDIO_DEFAULT_BASE_URL: 'http://127.0.0.1:4312',
  LM_STUDIO_DEFAULT_TARGET_URL: 'http://127.0.0.1:1234',
  CIRCUIT_RELAY_CODE: 290,
  MIME_TEXT_PLAIN: 'text/plain',
  WEBTRANSPORT_BOOTSTRAP_PEER_ID: '12D3KooWFhXabKDwALpzqMbto94sB7rvmZ6M28hs9Y9xSopDKwQr',
  BOOTSTRAP_PEER_IDS: ['12D3KooWFhXabKDwALpzqMbto94sB7rvmZ6M28hs9Y9xSopDKwQr'],
  ANALYTICS_WRAPPER: 'metered-analytics',
  ANALYTICS_APP_ID: 'metered',
}
